
export let SHOW_ERROR_TOAST = "SHOW_ERROR_TOAST";
export let RESET_TOAST = "RESET_TOAST";

// Auth actions
export let LOGIN = 'LOGIN';
export let LOGOUT = "LOGOUT"; 


//Home Action
export let MENU = "MENU"; 
export let GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID"; 
export let GET_PRODUCT_LISTING = "GET_PRODUCT_LISTING"; 
export let GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"; 
export let ADD_TO_CART = "ADD_TO_CART";
export let RESET_HOME_DATA = "RESET_HOME_DATA";
export let GET_SUMMARY = "GET_SUMMARY";







// Cart actions
export let GET_CART_ITEMS = "GET_CART_ITEMS";
export let GET_CARTID = "GET_CARTID";
export let REMOVE_ITEM = "REMOVE_ITEM";
export let DECREASE_QUANTITY = "DECREASE_QUANTITY";
export let RESET_CART_DATA = "RESET_CART_DATA";
export let RESET_CART_STATUS = "RESET_CART_STATUS";


// Gallery actions
export let RESET_GALLERY_ALBUM = "RESET_GALLERY_ALBUM";
export let GET_GALLERY_ALBUMS_LIST = "GET_GALLERY_ALBUMS_LIST";
export let GET_GALLERY_ALBUM="GET_GALLERY_ALBUMS";



// Raise Request Actions
export let GET_RAISED_REQUESTS = "GET_RAISED_REQUESTS";
export let SAVE_RAISED_REQUESTS = "SAVE_RAISED_REQUESTS";
export let RESET_SAVED_REQUEST_CHECK = "RESET_SAVED_REQUEST_CHECK";
export let CANCEL_RAISED_REQUEST = "CANCEL_RAISED_REQUEST";
export let RESET_CANCELLED_RAISED_REQUEST = "RESET_CANCELLED_RAISED_REQUEST";
export let UPLOAD_REQUEST_ATTACHMENT = "UPLOAD_REQUEST_ATTACHMENT";

// Attendance Actions
export let GET_ACTIVE_YEAR_BY_BRANCH_ID = "GET_ACTIVE_YEAR_BY_BRANCH_ID";
export let GET_FILTERED_STANDARD = "GET_FILTERED_STANDARD";
export let GET_SUBJECT_LIST = "GET_SUBJECT_LIST";
export let GET_STUDENT_ATTENDANCE  = "GET_STUDENT_ATTENDANCE";
export let GET_STUDENT_ATTENDANCE_GROUP  = "GET_STUDENT_ATTENDANCE_GROUP";
export let RESET_ATTENDANCE = "RESET_ATTENDANCE";
export let GET_GROUP_BY_BRANCH = "GET_GROUP_BY_BRANCH";
export let DEFAULTER_REPORT = "DEFAULTER_REPORT";
export let MARK_ATTENDANCE = "MARK_ATTENDANCE";
export let MARK_ATTENDANCE_GROUP = "MARK_ATTENDANCE_GROUP";





//Shopping Payment Action
export let ORDER_PLACED = "ORDER_PLACED";
export let SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK";
export let GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export let RESET_PAYMENT_DATA = "RESET_PAYMENT_DATA";

//Demo Action
export let GET_DEMO_REQUEST = "GET_DEMO_REQUEST";
export let RESET_DEMO_DATA = "RESET_DEMO_DATA";

//shopping products
export let GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export let GET_FILTER_OPTION = "GET_FILTER_OPTION";
export let SEARCH_PRODUCT_BY_NAME = "SEARCH_PRODUCT_BY_NAME";
export let RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST";
export let RESET_SEARCH_PRODUCT_LIST = "RESET_SEARCH_PRODUCT_LIST";
export let NOTIFY_ME = "NOTIFY_ME";
export let SAVE_REVIEW = "SAVE_REVIEW";



//Facility actions
export let GET_ALL_FACILITY = "GET_ALL_FACILITY";
export let GET_FACILITY_DETAIL = "GET_FACILITY_DETAIL";
export let GET_FACILITY_BOOKING_DETAIL = "GET_FACILITY_BOOKING_DETAIL";
export let GET_SINGLE_FACILITY_BOOKING_DETAIL = "GET_SINGLE_FACILITY_BOOKING_DETAIL";
export let GET_FACILITY_AVAILABEL_SLOT = "GET_FACILITY_AVAILABEL_SLOT";
export let FACILITY_RAISE_ENQUIRY ="FACILITY_RAISE_ENQUIRY";
export let BOOKED_FACILITY = "BOOKED_FACILITY";
export let CANCEL_BOOKED_FACILITY = "CANCEL_BOOKED_FACILITY";
export let RESET_FACILITY_DATA = "RESET_FACILITY_DATA";
export let GET_ALL_MEMBER_BY_BRANCHID="GET_ALL_MEMBER_BY_BRANCHID";
export let REMOVE_FACILITY_MEMBER ="REMOVE_FACILITY_MEMBER";
export let SAVE_FACILITY_MEMBER ="SAVE_FACILITY_MEMBER";
export let BLOCK_SELECTED_SLOT = "BLOCK_SELECTED_SLOT";


//Order actions
export let GET_ORDERS = "GET_ORDERS";
export let ORDER_DETAILS = "ORDER_DETAILS";
export let GET_INVOICES_BYORDER_ID = "GET_INVOICES_BYORDER_ID";
export let RESET_ORDER_DETAILS = "RESET_ORDER_DETAILS";
export let SAVE_RETURN_ORDER = "SAVE_RETURN_ORDER";
export let GET_COMPLAINTS_CATEGORY = "GET_COMPLAINTS_CATEGORY";
export let SAVE_COMPLAINTS = "SAVE_COMPLAINTS";
export let TRACK_ORDER = "TRACK_ORDER";

 
//Shopping Profile Action

export let GET_WISH_LIST = "GET_WISH_LIST";
export let GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";
export let RESET_PROFILE_DATA = "RESET_PROFILE_DATA";
export let DELETE_ADDRESS = "DELETE_ADDRESS";
export let GET_FEEDBACK_DETAILS = "GET_FEEDBACK_DETAILS";
export let GET_STATES = "GET_STATES";
export let ADD_ADDRESS = "ADD_ADDRESS";
export let GET_CUSTOMER_DETAILS = "GET_CUSTOMER_DETAILS";
export let RESET_WISH_LIST = "RESET_WISH_LIST";
export let DELETE_WISHLIST = "DELETE_WISHLIST";
export let GET_ALL_COMPLAINTS = "GET_ALL_COMPLAINTS";
export let GET_ALL_PRODUCTS_REVIEW = "GET_ALL_PRODUCTS_REVIEW"



//Teacher Action

export let GET_TEACHER_DETAILS = 'GET_TEACHER_DETAILS';
export let UPDATE_TEACHER_DETAILS = 'UPDATE_TEACHER_DETAILS';
export let GET_TEACHER_BY_BRANCH_ID = "GET_TEACHER_BY_BRANCH_ID";
export let GET_TEACHER_DETAIL_BY_ID = "GET_TEACHER_DETAIL_BY_ID";
export let RESET_TEACHER_DATA = "RESET_TEACHER_DATA";
export let GET_GROUPS = "GET_GROUPS";
export let GET_INDIVIDUAL_LIST = "GET_INDIVIDUAL_LIST";


// Time Table Actions
export let GET_TIMETABLE = "GET_TIMETABLE";
export let GET_TIMETABLE_BY_ID = "GET_TIMETABLE_BY_ID";
export let GET_TIMETABLE_SLOTS = "GET_TIMETABLE_SLOTS";
export let GET_HOLIDAY_LIST = "GET_HOLIDAY_LIST";
export let GET_TEACHER_TIMETABLE = "GET_TEACHER_TIMETABLE";
export let RESET_TIME_TABLE_DATA = "RESET_TIME_TABLE_DATA";




/**
 * Add all of your actions above these functions.
 *
 * @export
 * @param {*} action
 * @returns
 */
export function pending(action) {
    return action + "_PENDING";
}

export function fulfilled(action) {
    return action + "_FULFILLED";
}

export function rejected(action) {
    return action + "_REJECTED";
}