
export let SHOW_ERROR_TOAST = "SHOW_ERROR_TOAST";
export let RESET_TOAST = "RESET_TOAST";


//Payment Action 

export let GET_DUES = 'GET_DUES';
export let RESET_PAYMENT_STATUS = "RESET_PAYMENT_STATUS";
export let SUBMIT_DUES_REMARKS = "SUBMIT_DUES_REMARKS";
export let INIT_PAYMENT = "INIT_PAYMENT";
export let GET_PAYMENT_STATUS = "GET_PAYMENT_STATUS";
export let EMAIL_RECEIPT = "EMAIL_RECEIPT"; 
export let GET_ADDITIONAL_FEES = "GET_ADDITIONAL_FEES";
export let DELETE_ADDITIONAL_FEES = "DELETE_ADDITIONAL_FEES";
export let GET_FEE_INFO = "GET_FEE_INFO";
export let APPLY_FIRST_TIME_ADDITIONAL_FEES = "APPLY_FIRST_TIME_ADDITIONAL_FEES";
export let APPLY_ADDITIONAL_FEES = "APPLY_ADDITIONAL_FEES";
export let GET_UPI_MANDATE = "GET_UPI_MANDATE";
export let REVOKE_UPI_MANDATE = "REVOKE_UPI_MANDATE";
export let GET_STANDING_INSTRUCTION = "GET_STANDING_INSTRUCTION";
export let GET_STANDING_INSTRUCTION_VIEW = "GET_STANDING_INSTRUCTION_VIEW";
export let DELETE_STANDING_INSTRUCTION = "DELETE_STANDING_INSTRUCTION";
export let GET_PRINT_RECIEPT_DATA = "GET_PRINT_RECIEPT_DATA";
export let RESET_PRINT_RECIEPT_DATA = "RESET_PRINT_RECIEPT_DATA"


//Circular Action
export let GET_CIRCULARS = 'GET_CIRCULARS';
export let CIRCULAR_MARK_READ = 'CIRCULAR_MARK_READ';
export let GET_RECEIVED_CIRCULAR = 'GET_RECEIVED_CIRCULAR';
export let GET_SENT_CIRCULAR = 'GET_SENT_CIRCULAR';
export let GET_CIRCULAR_DETAILS = 'GET_CIRCULAR_DETAILS';
export let DELETE_CIRCULAR = 'DELETE_CIRCULAR';
export let RESET_CIRCULAR_VIEW_DATA = 'RESET_CIRCULAR_VIEW_DATA';
export let TEACHER_SENT_CIRCULAR = 'TEACHER_SENT_CIRCULAR';
export let DELETE_RECEIVED_CIRCULAR = 'DELETE_RECEIVED_CIRCULAR';




// Event Action
export let GET_EVENTS = 'GET_EVENTS';
export let GET_EVENT = 'GET_EVENT';
export let WRITE_EVENT_COMMENT = 'WRITE_EVENT_COMMENT';
export let EVENT_MARK_SEEN = 'EVENT_MARK_SEEN';
export let RESET_EVENT_VIEW_DATA = "RESET_EVENT_VIEW_DATA"; 
export let GET_SENT_EVENTS = "GET_SENT_EVENTS"; 
export let GET_RECEIVED_EVENTS = "GET_RECEIVED_EVENTS"; 
export let GET_EVENT_DETAILS = "GET_EVENT_DETAILS"; 
export let DELETE_EVENT = "DELETE_EVENT"; 
export let TEACHER_EVENT_SENT = "TEACHER_EVENT_SENT"; 



//Ediary Action
export let GET_EDIARY = 'GET_EDIARY';
export let GET_ONEEDIARY = 'GET_ONEEDIARY';
export let WRITE_EDIARYCOMMENT = 'WRITE_EDIARYCOMMENT';
export let EDIARYMARK_SEEN = 'EDIARYMARK_SEEN';
export let RESET_EDIARY_VIEW_DATA = 'RESET_EDIARY_VIEW_DATA';
export let GET_EDIARY_COMMENTS = 'GET_EDIARY_COMMENTS';
export let GET_SENT_EDIARY = "GET_SENT_EDIARY"; 
export let GET_RECEIVED_EDIARY = "GET_RECEIVED_EDIARY"; 
export let GET_EDIARY_VIEW = "GET_EDIARY_VIEW"; 
export let DELETE_EDIARY = "DELETE_EDIARY"; 
export let TEACHER_SENT_EDIARY = "TEACHER_SENT_EDIARY"; 
export let GET_CATEGORY_LIST = "GET_CATEGORY_LIST"; 



//Student Action
export let GET_STUDENT_DETAILS = 'GET_STUDENT_DETAILS';
export let RESET_UPDATE_STATUS ="RESET_UPDATE_STATUS";
export let UPDATE_STUDENT_DETAILS ="UPDATE_STUDENT_DETAILS";
export let UPDATE_AVATAR_BY_STUDENT ="UPDATE_AVATAR_BY_STUDENT";
export let SET_STUDENT_DETAILS = 'SET_STUDENT_DETAILS';
export let GET_PERFORMANCE_REPORT = "GET_PERFORMANCE_REPORT";
export let GET_CERTIFICATE = "GET_CERTIFICATE";
export let GET_STUDENT_ATTENDANCE_BY_MONTH = "GET_STUDENT_ATTENDANCE_BY_MONTH";
export let GET_GROUP_ATTENDANCE = "GET_GROUP_ATTENDANCE";
export let RESET_ATTENDANCE_VIEW_DATA= 'RESET_ATTENDANCE_VIEW_DATA';
export let GET_STANDARD_LIST = "GET_STANDARD_LIST";
export let GET_STUDENT_REPORT = "GET_STUDENT_REPORT";
export let RESET_STUDENT_DATA = "RESET_STUDENT_DATA";




//Institute Action
export let SEARCH_INSTITUTES = "SEARCH_INSTITUTES";
export let GET_INSTITUTE = "GET_INSTITUTE"; 
export let GET_CONFIGURED_MENU_LIST = "GET_CONFIGURED_MENU_LIST"; 
export let GET_BANNERS = 'GET_BANNERS';


// Branch actions
export let GET_INSTITUTE_ALL_BRANCHES = "GET_INSTITUTE_ALL_BRANCHES";
export let GET_BRANCH = "GET_BRANCH";
export let LIST_ACADEMIC_YEARS = "LIST_ACADEMIC_YEARS";

//Support Action

export let GET_SUPPORT_FOLDERS= 'GET_SUPPORT_FOLDERS';
export let GET_ARTICLES_FROM_A_FOLDER = 'GET_ARTICLES_FROM_A_FOLDER';
export let GET_LIST= 'GET_LIST';
export let SEARCH_ARTICLES= 'SEARCH_ARTICLES';
export let RESET_SUPPORT_DATA= 'RESET_SUPPORT_DATA';
export let NEW_TICKET= 'NEW_TICKET';


// UI Config Actions
export let GET_GLOBAL_UI_CONFIG = "GET_GLOBAL_UI_CONFIGS"
export let GET_CONSUMER_UI_CONFIG = "GET_CONSUMER_UI_CONFIG"
export let GET_BRANCH_UI_CONFIG = "GET_BRANCH_UI_CONFIG";
export let GET_FILTER_UI_CONFIG = "GET_FILTER_UI_CONFIG";
export let GET_FEES_UI_CONFIG = "GET_FEES_UI_CONFIG";
export let GET_PAYMENTS_UI_CONFIG = "GET_PAYMENTS_UI_CONFIG";
export let GET_FACILITY_UI_CONFIG = "GET_FACILITY_UI_CONFIG";


//Parent Action

export let GET_PARENT_DETAILS = "GET_PARENT_DETAILS";
export let RESET_PARENT_DETAILS = "RESET_PARENT_DETAILS";
export let LIST_STUDENTS = "LIST_STUDENTS";
export let UPDATE_PARENT_DETAILS = "UPDATE_PARENT_DETAILS";
export let UPDATE_AVATAR_BY_ROLE = "UPDATE_AVATAR_BY_ROLE";
export let RESET_UPDATE_RESPONSE = "RESET_UPDATE_RESPONSE";



//Assigments Action
export let GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export let UPLOAD_ASSIGNMENT = 'UPLOAD_ASSIGNMENT';
export let ASSIGNMENT_MARK_READ = 'ASSIGNMENT_MARK_READ';
export let RESET_ASSIGNMENT_VIEW_DATA = 'RESET_ASSIGNMENT_VIEW_DATA';
export let GET_RECEIVED_ASSIGNMENTS = 'GET_RECEIVED_ASSIGNMENTS';
export let GET_SENT_ASSIGNMENTS = 'GET_SENT_ASSIGNMENTS';
export let TEACHER_SENT_ASSIGNMENT = 'TEACHER_SENT_ASSIGNMENT';
export let DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export let DELETE_RECEIVED_ASSIGNMENT = 'DELETE_RECEIVED_ASSIGNMENT';




// Auth actions
export let LOGIN = 'LOGIN';
export let CLEAR_USERID_STATUS = "CLEAR_USERID_STATUS";
export let RESET_USER_STATE = "RESET_USER_STATE";
export let IS_OTP_BASED_LOGIN = "IS_OTP_BASED_LOGIN";
export let PASSWORD_LOGIN = 'PASSWORD_LOGIN';
export let RESET_USERNAME_CHECK = "RESET_USERNAME_CHECK";
export let GET_CONFIGURED_SECURITY_LABELS = "GET_CONFIGURED_SECURITY_LABELS";
export let RESET_SECURITY_LABELS = "RESET_SECURITY_LABELS";
export let GET_USER_ID = "GET_USER_ID";
export let SEND_OTP = "SEND_OTP";
export let OTP_LOGIN = "OTP_LOGIN";
export let RESET_PASSWORD_STATE = "RESET_PASSWORD_STATE";
export let GENERATE_PASSWORD_OTP = "GENERATE_PASSWORD_OTP";
export let RESET_PASSWORD = "RESET_PASSWORD";
export let GET_FORUM_SID = "GET_FORUM_SID";
export let LOGOUT = "LOGOUT"; 
export let GET_SHOPPING_DETAILS = "GET_SHOPPING_DETAILS"; 
export let RESET_SHOPPING_STATE = "RESET_SHOPPING_STATE"; 
export let GET_SHOPPING_PAYMENT_DETAILS = "GET_SHOPPING_PAYMENT_DETAILS";
export let CHECK_INVOICE_EXIST = "CHECK_INVOICE_EXIST";
export let RESET_USER = 'RESET_USER';
export let CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export let GET_USER_ID_CARD = 'GET_USER_ID_CARD';
export let SET_USER_DATA = 'SET_USER_DATA';
export let SET_USER_ROLE = 'SET_USER_ROLE';




//shopping categories
export let GET_CATEGORIES = "GET_CATEGORIES";
export let CATEGORIES_SET = "CATEGORIES_SET";
export let RESET_CATEGORIES = "RESET_CATEGORIES";
export let GET_SUBCATEGORIES = "GET_SUBCATEGORIES";

//shopping product details
export let GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export let RESET_PRODUCT_DETAILS = "RESET_PRODUCT_DETAILS";
export let PRODUCT_REVIEWS = "PRODUCT_REVIEWS";
export let DEMO_REQUEST = "DEMO_REQUEST";
export let ADD_WISHLIST = "ADD_WISHLIST";


// Cart actions
export let GET_CART_ITEMS = "GET_CART_ITEMS";
export let GET_CARTID = "GET_CARTID";
export let ADD_TO_CART = "ADD_TO_CART";
export let REMOVE_ITEM = "REMOVE_ITEM";
export let DECREASE_QUANTITY = "DECREASE_QUANTITY";
export let RESET_CART_DATA = "RESET_CART_DATA";
export let RESET_CART_STATUS = "RESET_CART_STATUS";


// Gallery actions
export let RESET_GALLERY_ALBUM = "RESET_GALLERY_ALBUM";
export let GET_GALLERY_ALBUMS_LIST = "GET_GALLERY_ALBUMS_LIST";
export let GET_GALLERY_ALBUM="GET_GALLERY_ALBUMS";



// Raise Request Actions
export let GET_RAISED_REQUESTS = "GET_RAISED_REQUESTS";
export let SAVE_RAISED_REQUESTS = "SAVE_RAISED_REQUESTS";
export let RESET_SAVED_REQUEST_CHECK = "RESET_SAVED_REQUEST_CHECK";
export let CANCEL_RAISED_REQUEST = "CANCEL_RAISED_REQUEST";
export let RESET_CANCELLED_RAISED_REQUEST = "RESET_CANCELLED_RAISED_REQUEST";
export let UPLOAD_REQUEST_ATTACHMENT = "UPLOAD_REQUEST_ATTACHMENT";

// Attendance Actions
export let GET_ACTIVE_YEAR_BY_BRANCH_ID = "GET_ACTIVE_YEAR_BY_BRANCH_ID";
export let GET_FILTERED_STANDARD = "GET_FILTERED_STANDARD";
export let GET_SUBJECT_LIST = "GET_SUBJECT_LIST";
export let GET_STUDENT_ATTENDANCE  = "GET_STUDENT_ATTENDANCE";
export let GET_STUDENT_ATTENDANCE_GROUP  = "GET_STUDENT_ATTENDANCE_GROUP";
export let RESET_ATTENDANCE = "RESET_ATTENDANCE";
export let GET_GROUP_BY_BRANCH = "GET_GROUP_BY_BRANCH";
export let DEFAULTER_REPORT = "DEFAULTER_REPORT";
export let MARK_ATTENDANCE = "MARK_ATTENDANCE";
export let MARK_ATTENDANCE_GROUP = "MARK_ATTENDANCE_GROUP";





//Shopping Payment Action
export let ORDER_PLACED = "ORDER_PLACED";
export let SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK";
export let GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export let RESET_PAYMENT_DATA = "RESET_PAYMENT_DATA";

//Demo Action
export let GET_DEMO_REQUEST = "GET_DEMO_REQUEST";
export let RESET_DEMO_DATA = "RESET_DEMO_DATA";

//shopping products
export let GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export let GET_FILTER_OPTION = "GET_FILTER_OPTION";
export let SEARCH_PRODUCT_BY_NAME = "SEARCH_PRODUCT_BY_NAME";
export let RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST";
export let RESET_SEARCH_PRODUCT_LIST = "RESET_SEARCH_PRODUCT_LIST";
export let NOTIFY_ME = "NOTIFY_ME";
export let SAVE_REVIEW = "SAVE_REVIEW";



//Facility actions
export let GET_ALL_FACILITY = "GET_ALL_FACILITY";
export let GET_FACILITY_DETAIL = "GET_FACILITY_DETAIL";
export let GET_FACILITY_BOOKING_DETAIL = "GET_FACILITY_BOOKING_DETAIL";
export let GET_SINGLE_FACILITY_BOOKING_DETAIL = "GET_SINGLE_FACILITY_BOOKING_DETAIL";
export let GET_FACILITY_AVAILABEL_SLOT = "GET_FACILITY_AVAILABEL_SLOT";
export let FACILITY_RAISE_ENQUIRY ="FACILITY_RAISE_ENQUIRY";
export let BOOKED_FACILITY = "BOOKED_FACILITY";
export let CANCEL_BOOKED_FACILITY = "CANCEL_BOOKED_FACILITY";
export let RESET_FACILITY_DATA = "RESET_FACILITY_DATA";
export let GET_ALL_MEMBER_BY_BRANCHID="GET_ALL_MEMBER_BY_BRANCHID";
export let REMOVE_FACILITY_MEMBER ="REMOVE_FACILITY_MEMBER";
export let SAVE_FACILITY_MEMBER ="SAVE_FACILITY_MEMBER";
export let BLOCK_SELECTED_SLOT = "BLOCK_SELECTED_SLOT";


//Order actions
export let GET_ORDERS = "GET_ORDERS";
export let ORDER_DETAILS = "ORDER_DETAILS";
export let GET_INVOICES_BYORDER_ID = "GET_INVOICES_BYORDER_ID";
export let RESET_ORDER_DETAILS = "RESET_ORDER_DETAILS";
export let SAVE_RETURN_ORDER = "SAVE_RETURN_ORDER";
export let GET_COMPLAINTS_CATEGORY = "GET_COMPLAINTS_CATEGORY";
export let SAVE_COMPLAINTS = "SAVE_COMPLAINTS";
export let TRACK_ORDER = "TRACK_ORDER";

 
//Shopping Profile Action

export let GET_WISH_LIST = "GET_WISH_LIST";
export let GET_PROFILE_DETAILS = "GET_PROFILE_DETAILS";
export let RESET_PROFILE_DATA = "RESET_PROFILE_DATA";
export let DELETE_ADDRESS = "DELETE_ADDRESS";
export let GET_FEEDBACK_DETAILS = "GET_FEEDBACK_DETAILS";
export let GET_STATES = "GET_STATES";
export let ADD_ADDRESS = "ADD_ADDRESS";
export let GET_CUSTOMER_DETAILS = "GET_CUSTOMER_DETAILS";
export let RESET_WISH_LIST = "RESET_WISH_LIST";
export let DELETE_WISHLIST = "DELETE_WISHLIST";
export let GET_ALL_COMPLAINTS = "GET_ALL_COMPLAINTS";
export let GET_ALL_PRODUCTS_REVIEW = "GET_ALL_PRODUCTS_REVIEW"



//Teacher Action

export let GET_TEACHER_DETAILS = 'GET_TEACHER_DETAILS';
export let UPDATE_TEACHER_DETAILS = 'UPDATE_TEACHER_DETAILS';
export let GET_TEACHER_BY_BRANCH_ID = "GET_TEACHER_BY_BRANCH_ID";
export let GET_TEACHER_DETAIL_BY_ID = "GET_TEACHER_DETAIL_BY_ID";
export let RESET_TEACHER_DATA = "RESET_TEACHER_DATA";
export let GET_GROUPS = "GET_GROUPS";
export let GET_INDIVIDUAL_LIST = "GET_INDIVIDUAL_LIST";


// Time Table Actions
export let GET_TIMETABLE = "GET_TIMETABLE";
export let GET_TIMETABLE_BY_ID = "GET_TIMETABLE_BY_ID";
export let GET_TIMETABLE_SLOTS = "GET_TIMETABLE_SLOTS";
export let GET_HOLIDAY_LIST = "GET_HOLIDAY_LIST";
export let GET_TEACHER_TIMETABLE = "GET_TEACHER_TIMETABLE";
export let RESET_TIME_TABLE_DATA = "RESET_TIME_TABLE_DATA";




/**
 * Add all of your actions above these functions.
 *
 * @export
 * @param {*} action
 * @returns
 */
export function pending(action) {
    return action + "_PENDING";
}

export function fulfilled(action) {
    return action + "_FULFILLED";
}

export function rejected(action) {
    return action + "_REJECTED";
}